[API_PARSING]
# full path to logs storage directory
log_dir = ''
# recommended value, see https://docs.python.org/3/library/logging.html#logging-levels for more
log_lvl = 'logging.INFO'

[CHECK_NEWCOMERS]
# OGame server ID
server = ''
# OGame community ID
community = ''
# full path to data storage directory
data_dir = ''

[DISCORD_BOT]
